#!/usr/bin/env node
// Regenerates the GENERATED sections of the docs site from repo state:
//   - map.mdx "inventory" section (counts of tokens, components, commands, agents)
//   - decisions/index.mdx "adr-index" section (list built from ADR frontmatter)
// Idempotent: same repo state → same output. Run via /ply-update-docs or directly:
//   node scripts/gen-map.mjs
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MAP = path.join(ROOT, "apps/docs/src/content/docs/map.mdx");
const ADR_DIR = path.join(ROOT, "apps/docs/src/content/docs/decisions");
const ADR_INDEX = path.join(ADR_DIR, "index.mdx");
const TOKENS = path.join(ROOT, "packages/tokens/src/ply.tokens.json");
const COMMANDS_DIR = path.join(ROOT, ".claude/commands");
const AGENTS_DIR = path.join(ROOT, ".claude/agents");
const REACT_SRC = path.join(ROOT, "packages/react/src");

function replaceSection(file, sectionName, newBody) {
  const lines = readFileSync(file, "utf8").split("\n");
  const begin = lines.findIndex((l) => l.includes(`GENERATED:BEGIN ${sectionName}`));
  const end = lines.findIndex((l) => l.includes(`GENERATED:END ${sectionName}`));
  if (begin === -1 || end === -1 || end <= begin) {
    throw new Error(`GENERATED markers for "${sectionName}" not found in ${file}`);
  }
  const out = [
    ...lines.slice(0, begin + 1),
    "",
    ...newBody.trim().split("\n"),
    "",
    ...lines.slice(end),
  ].join("\n");
  writeFileSync(file, out);
}

function frontmatterField(src, field) {
  const m = src.match(new RegExp(`^${field}:\\s*"?(.*?)"?\\s*$`, "m"));
  return m ? m[1] : null;
}

function listDir(dir, filter) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).filter(filter);
}

// --- Token counts (available from Phase 4 on) ---
let tokenLine = "- **Tokens:** — _(pipeline lands in Phase 4)_";
if (existsSync(TOKENS)) {
  const dtcg = JSON.parse(readFileSync(TOKENS, "utf8"));
  let count = 0;
  const collections = [];
  const walk = (node) => {
    for (const [key, val] of Object.entries(node)) {
      if (key.startsWith("$") || typeof val !== "object" || val === null) continue;
      if ("$value" in val) count += 1;
      else walk(val);
    }
  };
  for (const [name, group] of Object.entries(dtcg)) {
    if (name.startsWith("$") || typeof group !== "object") continue;
    collections.push(name);
    walk(group);
  }
  tokenLine = `- **Tokens:** ${count} across ${collections.length} collections (${collections.join(", ")})`;
}

// --- Components ---
const components = listDir(REACT_SRC, (d) => /^[A-Z]/.test(d));
const componentLine = components.length
  ? `- **Components (code):** ${components.length} — ${components.join(", ")}`
  : "- **Components:** — _(design starts in Phase 5, code in Phase 6)_";

// --- Commands & agents ---
const commands = listDir(COMMANDS_DIR, (f) => f.endsWith(".md")).map(
  (f) => `\`/${f.replace(/\.md$/, "")}\``
);
const agents = listDir(AGENTS_DIR, (f) => f.endsWith(".md")).map((f) =>
  f.replace(/\.md$/, "")
);

// --- Knowledge base ---
const KB = path.join(ROOT, "kb");
const kbCount = (sub) => listDir(path.join(KB, sub), (f) => f.endsWith(".md")).length;
const kbLine = `- **Knowledge base:** ${kbCount("systems")} system dossiers, ${kbCount("topics")} topic guides, ${kbCount("comparisons")} decision comparisons`;

replaceSection(
  MAP,
  "inventory",
  `## Inventory

_Regenerated by \`scripts/gen-map.mjs\` (run via \`/ply-update-docs\`)._

${tokenLine}
${componentLine}
${kbLine}
- **Commands:** ${commands.join(", ") || "—"}
- **Agents:** ${agents.join(", ") || "—"}
- **Decisions:** ${listDir(ADR_DIR, (f) => f.startsWith("adr-")).length} ADRs`
);

// --- ADR index ---
const adrs = listDir(ADR_DIR, (f) => f.startsWith("adr-") && f.endsWith(".mdx")).sort();
const items = adrs.map((f) => {
  const src = readFileSync(path.join(ADR_DIR, f), "utf8");
  const title = frontmatterField(src, "title") ?? f;
  const desc = frontmatterField(src, "description") ?? "";
  const status = frontmatterField(src, "status") ?? "unknown";
  const slug = f.replace(/\.mdx$/, "");
  return `- [${title}](/decisions/${slug}/) — ${desc} (${status})`;
});
replaceSection(ADR_INDEX, "adr-index", items.join("\n"));

console.log(
  `gen-map: inventory updated (${commands.length} commands, ${agents.length} agents, ${adrs.length} ADRs)`
);
