// Style Dictionary build for Ply tokens (ADR-0003, ADR-0007).
// Outputs:
//   dist/css/ply.css   — :root (light + scales + Brand-1 ramp) · [data-theme="dark"] (semantic dark
//                        + ramp re-declared so cascade order stays correct) · [data-brand="brand-2"]
//                        (ramp only — semantic vars reference the ramp via var(), so they follow) ·
//                        [data-font="…"] font overrides
//   dist/ts/tokens.ts  — typed path → { cssVar, value } map
// Color primitives are sources for alias resolution but are NEVER emitted; the colors-brand ramp
// IS emitted (it is the live brand axis in CSS).
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PKG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const val = (t) => t.$value ?? t.value;

StyleDictionary.registerTransform({
  name: "name/ply",
  type: "name",
  transform: (t) => ("ply-" + t.path.join("-")).toLowerCase(),
});
StyleDictionary.registerTransform({
  name: "value/ply-font-family",
  type: "value",
  filter: (t) => (t.$type ?? t.type) === "fontFamily",
  transform: (t) => {
    const v = val(t);
    return Array.isArray(v) ? v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ") : v;
  },
});
StyleDictionary.registerFormat({
  name: "ts/ply",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => {
      const p = t.path.join(".");
      return `  "${p}": { cssVar: "--${t.name}", value: ${JSON.stringify(val(t))} }`;
    });
    return [
      "// GENERATED by @ply/tokens build — do not hand-edit.",
      "export const tokens = {",
      entries.join(",\n"),
      "} as const;",
      "export type TokenPath = keyof typeof tokens;",
      "export const cssVar = (p: TokenPath): string => `var(${tokens[p].cssVar})`;",
      "",
    ].join("\n");
  },
});

const TRANSFORMS = ["name/ply", "value/ply-font-family"];
const src = (f) => path.join(PKG, "src", f);
const isColorPrimitive = (t) => t.filePath.includes("primitives") && (t.$type ?? t.type) === "color";
const isBrand = (t) => t.path[0] === "colors-brand";
const inFile = (frag) => (t) => t.filePath.includes(frag);
// semantic vars that alias the brand ramp stay live var() references so the brand axis works in CSS
const refsBrand = (t) => typeof t.original?.$value === "string" && t.original.$value.startsWith("{colors-brand.");

const builds = [
  {
    // :root — scales + font defaults + Brand-1 ramp + semantic light
    source: [src("primitives.tokens.json"), src("brand.brand-1.tokens.json"), src("semantic.light.tokens.json")],
    css: {
      destination: "_light.css",
      filter: (t) => inFile("semantic.light")(t) || isBrand(t) || (inFile("primitives")(t) && !isColorPrimitive(t)),
      options: { selector: ":root", outputReferences: refsBrand },
    },
    ts: {
      destination: "tokens.ts",
      filter: (t) => inFile("semantic.light")(t) || isBrand(t) || (inFile("primitives")(t) && !isColorPrimitive(t)),
    },
  },
  {
    // dark — semantic dark + ramp re-declared (keeps cascade order deterministic for dark+brand-2)
    source: [src("primitives.tokens.json"), src("brand.brand-1.tokens.json"), src("semantic.dark.tokens.json")],
    css: {
      destination: "_dark.css",
      filter: (t) => inFile("semantic.dark")(t) || isBrand(t),
      options: { selector: '[data-theme="dark"]', outputReferences: refsBrand },
    },
  },
  {
    // brand-2 — ramp only; must come AFTER the dark block in the stitched file
    source: [src("primitives.tokens.json"), src("brand.brand-2.tokens.json")],
    css: {
      destination: "_brand2.css",
      filter: isBrand,
      options: { selector: '[data-brand="brand-2"]' },
    },
  },
  {
    source: [src("font.geist.tokens.json")],
    css: { destination: "_font-geist.css", filter: () => true, options: { selector: '[data-font="geist"]' } },
  },
  {
    source: [src("font.die-grotesk-a.tokens.json")],
    css: { destination: "_font-dga.css", filter: () => true, options: { selector: '[data-font="die-grotesk-a"]' } },
  },
];

const cssParts = [];
for (const b of builds) {
  const platforms = {
    css: {
      transforms: TRANSFORMS,
      buildPath: path.join(PKG, "dist/css/"),
      files: [{ format: "css/variables", ...b.css }],
    },
  };
  if (b.ts) {
    platforms.ts = {
      transforms: TRANSFORMS,
      buildPath: path.join(PKG, "dist/ts/"),
      files: [{ format: "ts/ply", ...b.ts }],
    };
  }
  const sd = new StyleDictionary({ source: b.source, platforms });
  await sd.buildAllPlatforms();
  cssParts.push(b.css.destination);
}

// Stitch the final stylesheet in cascade order, then drop the intermediates.
const stitched = cssParts
  .map((f) => readFileSync(path.join(PKG, "dist/css", f), "utf8"))
  .join("\n");
writeFileSync(
  path.join(PKG, "dist/css/ply.css"),
  "/* GENERATED by @ply/tokens build — do not hand-edit. Source: src/*.tokens.json */\n" + stitched
);
for (const f of cssParts) rmSync(path.join(PKG, "dist/css", f));
console.log("sd: dist/css/ply.css + dist/ts/tokens.ts written");
