// Style Dictionary build for Ply tokens (ADR-0003, ADR-0005).
// Outputs:
//   dist/css/ply.css   — :root (light + scales) then [data-theme="dark"] overrides (semantic only)
//   dist/ts/tokens.ts  — typed path → { cssVar, light, dark } map
// Color primitives are sources for alias resolution but are NEVER emitted (ADR-0005).
import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const PKG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const val = (t) => t.$value ?? t.value;

StyleDictionary.registerTransform({
  name: "name/ply",
  type: "name",
  transform: (t) => "ply-" + t.path.join("-"),
});
StyleDictionary.registerTransform({
  name: "value/ply-font-family",
  type: "value",
  filter: (t) => (t.$type ?? t.type) === "fontFamily",
  transform: (t) => {
    const v = val(t);
    return Array.isArray(v) ? v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ") : v;
  },
});
StyleDictionary.registerFormat({
  name: "ts/ply",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((t) => {
      const p = t.path.join(".");
      return `  "${p}": { cssVar: "--${t.name}", value: ${JSON.stringify(val(t))} }`;
    });
    return [
      "// GENERATED by @ply/tokens build — do not hand-edit.",
      "export const tokens = {",
      entries.join(",\n"),
      "} as const;",
      "export type TokenPath = keyof typeof tokens;",
      "export const cssVar = (p: TokenPath): string => `var(${tokens[p].cssVar})`;",
      "",
    ].join("\n");
  },
});

const TRANSFORMS = ["name/ply", "value/ply-font-family"];
const isColorPrimitive = (t) => t.filePath.includes("primitives") && (t.$type ?? t.type) === "color";
const isSemantic = (mode) => (t) => t.filePath.includes(`semantic.${mode}`);

const light = new StyleDictionary({
  source: [path.join(PKG, "src/primitives.tokens.json"), path.join(PKG, "src/semantic.light.tokens.json")],
  platforms: {
    css: {
      transforms: TRANSFORMS,
      buildPath: path.join(PKG, "dist/css/"),
      files: [{
        destination: "_light.css",
        format: "css/variables",
        filter: (t) => isSemantic("light")(t) || (t.filePath.includes("primitives") && !isColorPrimitive(t)),
        options: { selector: ":root" },
      }],
    },
    ts: {
      transforms: TRANSFORMS,
      buildPath: path.join(PKG, "dist/ts/"),
      files: [{
        destination: "tokens.ts",
        format: "ts/ply",
        filter: (t) => isSemantic("light")(t) || (t.filePath.includes("primitives") && !isColorPrimitive(t)),
      }],
    },
  },
});
const dark = new StyleDictionary({
  source: [path.join(PKG, "src/primitives.tokens.json"), path.join(PKG, "src/semantic.dark.tokens.json")],
  platforms: {
    css: {
      transforms: TRANSFORMS,
      buildPath: path.join(PKG, "dist/css/"),
      files: [{
        destination: "_dark.css",
        format: "css/variables",
        filter: isSemantic("dark"),
        options: { selector: '[data-theme="dark"]' },
      }],
    },
  },
});
await light.buildAllPlatforms();
await dark.buildAllPlatforms();

// Stitch the final stylesheet, then drop the intermediates.
const lightCss = readFileSync(path.join(PKG, "dist/css/_light.css"), "utf8");
const darkCss = readFileSync(path.join(PKG, "dist/css/_dark.css"), "utf8");
writeFileSync(
  path.join(PKG, "dist/css/ply.css"),
  "/* GENERATED by @ply/tokens build — do not hand-edit. Source: src/*.tokens.json */\n" + lightCss + "\n" + darkCss
);
rmSync(path.join(PKG, "dist/css/_light.css"));
rmSync(path.join(PKG, "dist/css/_dark.css"));
console.log("sd: dist/css/ply.css + dist/ts/tokens.ts written");
